package fis.poo.cinefis.vista;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

public class VistaCompra extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaCompra.class.getName());

    /**
     * Creates new form VistaCompra
     */
    public VistaCompra() {
        initComponents();
        setTitle("CINEFIS - Compra de Entradas");
        setSize(950, 700);
        setLocationRelativeTo(null);
        setResizable(false);

        configurarTabla();

        lblImgCanguil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/snacks/canguil.png")));
        lblImgGaseosa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/snacks/gaseosa.png")));
        lblImgNachos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/snacks/nachos.png")));
        
        configurarSpinnersSnacks();
        configurarEventosSnacks();
    }

    public VistaCompra(ArrayList<String> asientosSeleccionados) {
        initComponents();
        setTitle("CINEFIS - Compra de Entradas");
        setSize(950, 700);
        setLocationRelativeTo(null);
        setResizable(false);

        configurarTabla();
        cargarAsientos(asientosSeleccionados);

        lblImgCanguil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/snacks/canguil.png")));
        lblImgGaseosa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/snacks/gaseosa.png")));
        lblImgNachos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/snacks/nachos.png")));
        
        configurarSpinnersSnacks();
        configurarEventosSnacks();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblSubtitulo = new javax.swing.JLabel();
        panelEntradas = new javax.swing.JPanel();
        lblEntradas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEntradas = new javax.swing.JTable();
        panelSnacks = new javax.swing.JPanel();
        lblSnacks = new javax.swing.JLabel();
        chkCanguil = new javax.swing.JCheckBox();
        spnCanguil = new javax.swing.JSpinner();
        chkGaseosa = new javax.swing.JCheckBox();
        spnGaseosa = new javax.swing.JSpinner();
        chkNachos = new javax.swing.JCheckBox();
        spnNachos = new javax.swing.JSpinner();
        panelImgCanguil = new javax.swing.JPanel();
        lblImgCanguil = new javax.swing.JLabel();
        panelImgNachos = new javax.swing.JPanel();
        lblImgNachos = new javax.swing.JLabel();
        panelImgGaseosa = new javax.swing.JPanel();
        lblImgGaseosa = new javax.swing.JLabel();
        panelTotales = new javax.swing.JPanel();
        lblSubtotalEntradas = new javax.swing.JLabel();
        lblSubtotalSnacks = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        panelBotones = new javax.swing.JPanel();
        btnCalcular = new javax.swing.JButton();
        btnContinuar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CINEFIS - Compra de Entradas");
        setMinimumSize(new java.awt.Dimension(950, 700));
        setResizable(false);

        panelPrincipal.setBackground(new java.awt.Color(10, 14, 20));
        panelPrincipal.setPreferredSize(new java.awt.Dimension(950, 700));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 38)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(218, 165, 32));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("CINEFIS");

        lblSubtitulo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblSubtitulo.setForeground(new java.awt.Color(240, 240, 240));
        lblSubtitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSubtitulo.setText("Datos de compra");

        panelEntradas.setBackground(new java.awt.Color(18, 28, 38));
        panelEntradas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(218, 165, 32)));
        panelEntradas.setMinimumSize(new java.awt.Dimension(620, 360));
        panelEntradas.setPreferredSize(new java.awt.Dimension(620, 360));

        lblEntradas.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblEntradas.setForeground(new java.awt.Color(240, 240, 240));
        lblEntradas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEntradas.setText("Entradas seleccionadas");

        tablaEntradas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaEntradas);

        javax.swing.GroupLayout panelEntradasLayout = new javax.swing.GroupLayout(panelEntradas);
        panelEntradas.setLayout(panelEntradasLayout);
        panelEntradasLayout.setHorizontalGroup(
            panelEntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEntradasLayout.createSequentialGroup()
                .addGroup(panelEntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEntradasLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelEntradasLayout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(lblEntradas)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelEntradasLayout.setVerticalGroup(
            panelEntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEntradasLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblEntradas)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelSnacks.setBackground(new java.awt.Color(18, 28, 38));
        panelSnacks.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(218, 165, 32)));
        panelSnacks.setPreferredSize(new java.awt.Dimension(260, 360));

        lblSnacks.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblSnacks.setForeground(new java.awt.Color(240, 240, 240));
        lblSnacks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSnacks.setText("Snacks opcionales");

        chkCanguil.setBackground(new java.awt.Color(18, 28, 38));
        chkCanguil.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chkCanguil.setForeground(new java.awt.Color(240, 240, 240));
        chkCanguil.setText("Canguil $2.50");

        chkGaseosa.setBackground(new java.awt.Color(18, 28, 38));
        chkGaseosa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chkGaseosa.setForeground(new java.awt.Color(240, 240, 240));
        chkGaseosa.setText("Gaseosa $1.50");

        chkNachos.setBackground(new java.awt.Color(18, 28, 38));
        chkNachos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chkNachos.setForeground(new java.awt.Color(240, 240, 240));
        chkNachos.setText("Nachos $3.00");

        panelImgCanguil.setBackground(new java.awt.Color(30, 40, 52));
        panelImgCanguil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(218, 165, 32)));
        panelImgCanguil.setPreferredSize(new java.awt.Dimension(80, 80));

        lblImgCanguil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelImgCanguilLayout = new javax.swing.GroupLayout(panelImgCanguil);
        panelImgCanguil.setLayout(panelImgCanguilLayout);
        panelImgCanguilLayout.setHorizontalGroup(
            panelImgCanguilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImgCanguilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImgCanguil, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelImgCanguilLayout.setVerticalGroup(
            panelImgCanguilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImgCanguilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImgCanguil, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelImgNachos.setBackground(new java.awt.Color(30, 40, 52));
        panelImgNachos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(218, 165, 32)));
        panelImgNachos.setPreferredSize(new java.awt.Dimension(80, 80));

        lblImgNachos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelImgNachosLayout = new javax.swing.GroupLayout(panelImgNachos);
        panelImgNachos.setLayout(panelImgNachosLayout);
        panelImgNachosLayout.setHorizontalGroup(
            panelImgNachosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImgNachosLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(lblImgNachos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelImgNachosLayout.setVerticalGroup(
            panelImgNachosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImgNachosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImgNachos, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelImgGaseosa.setBackground(new java.awt.Color(30, 40, 52));
        panelImgGaseosa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(218, 165, 32)));
        panelImgGaseosa.setPreferredSize(new java.awt.Dimension(80, 80));

        lblImgGaseosa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelImgGaseosaLayout = new javax.swing.GroupLayout(panelImgGaseosa);
        panelImgGaseosa.setLayout(panelImgGaseosaLayout);
        panelImgGaseosaLayout.setHorizontalGroup(
            panelImgGaseosaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImgGaseosaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImgGaseosa, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelImgGaseosaLayout.setVerticalGroup(
            panelImgGaseosaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImgGaseosaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImgGaseosa, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelSnacksLayout = new javax.swing.GroupLayout(panelSnacks);
        panelSnacks.setLayout(panelSnacksLayout);
        panelSnacksLayout.setHorizontalGroup(
            panelSnacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSnacksLayout.createSequentialGroup()
                .addGroup(panelSnacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSnacksLayout.createSequentialGroup()
                        .addContainerGap(14, Short.MAX_VALUE)
                        .addGroup(panelSnacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelImgNachos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelSnacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(panelImgGaseosa, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(panelImgCanguil, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelSnacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelSnacksLayout.createSequentialGroup()
                                .addGroup(panelSnacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkGaseosa)
                                    .addComponent(chkNachos))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelSnacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(spnGaseosa, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(spnNachos, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelSnacksLayout.createSequentialGroup()
                                .addComponent(chkCanguil)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(spnCanguil, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelSnacksLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblSnacks)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelSnacksLayout.setVerticalGroup(
            panelSnacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSnacksLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblSnacks)
                .addGroup(panelSnacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSnacksLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(panelSnacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkCanguil)
                            .addComponent(spnCanguil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelSnacksLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(panelImgCanguil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(panelSnacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSnacksLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(panelImgGaseosa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE))
                    .addGroup(panelSnacksLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(panelSnacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkGaseosa)
                            .addComponent(spnGaseosa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(panelSnacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelImgNachos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSnacksLayout.createSequentialGroup()
                        .addGroup(panelSnacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkNachos)
                            .addComponent(spnNachos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)))
                .addGap(25, 25, 25))
        );

        panelTotales.setBackground(new java.awt.Color(18, 28, 38));
        panelTotales.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(218, 165, 32)));
        panelTotales.setPreferredSize(new java.awt.Dimension(890, 100));

        lblSubtotalEntradas.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblSubtotalEntradas.setForeground(new java.awt.Color(218, 165, 32));
        lblSubtotalEntradas.setText("Subtotal entradas: $0.00");

        lblSubtotalSnacks.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblSubtotalSnacks.setForeground(new java.awt.Color(218, 165, 32));
        lblSubtotalSnacks.setText("Subtotal snacks: $0.00");

        lblTotal.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(218, 165, 32));
        lblTotal.setText("Total: $0.00");

        javax.swing.GroupLayout panelTotalesLayout = new javax.swing.GroupLayout(panelTotales);
        panelTotales.setLayout(panelTotalesLayout);
        panelTotalesLayout.setHorizontalGroup(
            panelTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTotalesLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotal)
                    .addComponent(lblSubtotalEntradas)
                    .addComponent(lblSubtotalSnacks))
                .addContainerGap(680, Short.MAX_VALUE))
        );
        panelTotalesLayout.setVerticalGroup(
            panelTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTotalesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSubtotalEntradas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSubtotalSnacks)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotal)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        panelBotones.setBackground(new java.awt.Color(10, 14, 20));

        btnCalcular.setBackground(new java.awt.Color(218, 165, 32));
        btnCalcular.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnCalcular.setText("CALCULAR TOTAL");
        btnCalcular.setFocusable(false);

        btnContinuar.setBackground(new java.awt.Color(218, 165, 32));
        btnContinuar.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnContinuar.setText("CONTINUAR");
        btnContinuar.setFocusable(false);

        btnVolver.setBackground(new java.awt.Color(30, 40, 52));
        btnVolver.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(240, 240, 240));
        btnVolver.setText("VOLVER");
        btnVolver.setFocusable(false);

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addContainerGap(482, Short.MAX_VALUE)
                .addComponent(btnCalcular)
                .addGap(18, 18, 18)
                .addComponent(btnContinuar)
                .addGap(18, 18, 18)
                .addComponent(btnVolver)
                .addContainerGap())
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcular)
                    .addComponent(btnContinuar)
                    .addComponent(btnVolver))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblSubtitulo))
                    .addComponent(lblTitulo))
                .addGap(375, 375, 375))
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(panelTotales, javax.swing.GroupLayout.PREFERRED_SIZE, 882, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelPrincipalLayout.createSequentialGroup()
                            .addComponent(panelEntradas, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(panelSnacks, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSubtitulo)
                .addGap(18, 18, 18)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelSnacks, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                    .addComponent(panelEntradas, javax.swing.GroupLayout.PREFERRED_SIZE, 350, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelTotales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaCompra().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnContinuar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JCheckBox chkCanguil;
    private javax.swing.JCheckBox chkGaseosa;
    private javax.swing.JCheckBox chkNachos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEntradas;
    private javax.swing.JLabel lblImgCanguil;
    private javax.swing.JLabel lblImgGaseosa;
    private javax.swing.JLabel lblImgNachos;
    private javax.swing.JLabel lblSnacks;
    private javax.swing.JLabel lblSubtitulo;
    private javax.swing.JLabel lblSubtotalEntradas;
    private javax.swing.JLabel lblSubtotalSnacks;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelEntradas;
    private javax.swing.JPanel panelImgCanguil;
    private javax.swing.JPanel panelImgGaseosa;
    private javax.swing.JPanel panelImgNachos;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelSnacks;
    private javax.swing.JPanel panelTotales;
    private javax.swing.JSpinner spnCanguil;
    private javax.swing.JSpinner spnGaseosa;
    private javax.swing.JSpinner spnNachos;
    private javax.swing.JTable tablaEntradas;
    // End of variables declaration//GEN-END:variables
    

    private void configurarTabla() {
        DefaultTableModel modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                // Solo se permite editar la columna Edad
                return column == 1;
            }
        };

        modelo.addColumn("Asiento");
        modelo.addColumn("Edad");
        modelo.addColumn("Tipo cliente");
        modelo.addColumn("Precio");

        tablaEntradas.setModel(modelo);

        // Evita que el usuario mueva las columnas
        tablaEntradas.getTableHeader().setReorderingAllowed(false);
    }

    private void cargarAsientos(ArrayList<String> asientosSeleccionados) {
        DefaultTableModel modelo = (DefaultTableModel) tablaEntradas.getModel();

        for (String asiento : asientosSeleccionados) {
            modelo.addRow(new Object[]{asiento, "", "", ""});
        }
    }      
    
    //Obtener cantidad de entradas
    public int obtenerCantidadEntradas() {
        return tablaEntradas.getRowCount();
    }
    
    //Obtener asiento de una fila
    public String obtenerAsiento(int fila) {
        Object valor = tablaEntradas.getValueAt(fila, 0);
        if (valor == null) {
            return "";
        }
        return valor.toString().trim();
    }
    
    //Obtener la edad escrita
    public String obtenerEdad(int fila) {
        Object valor = tablaEntradas.getValueAt(fila, 1);
        if (valor == null) {
            return "";
        }
        return valor.toString().trim();
    }
    
    //Mostrar el resultado calculado
    public void mostrarResultadoEntrada(int fila, String tipoCliente, double precio) {
        tablaEntradas.setValueAt(tipoCliente, fila, 2);
        tablaEntradas.setValueAt(
                String.format("$%.2f", precio),
                fila,
                3
        );
    }
    
    //Limpiar resultados anteriores
    public void limpiarResultadosEntradas() {
        for (int fila = 0; fila < tablaEntradas.getRowCount(); fila++) {
            tablaEntradas.setValueAt("", fila, 2);
            tablaEntradas.setValueAt("", fila, 3);
        }
        mostrarTotales(0, 0, 0);
    }
    
    //mostrar totales
    public void mostrarTotales(double subtotalEntradas, double subtotalSnacks, double total) {
        lblSubtotalEntradas.setText(
                String.format(
                        "Subtotal entradas: $%.2f",
                        subtotalEntradas
                )
        );
        lblSubtotalSnacks.setText(
                String.format(
                        "Subtotal snacks: $%.2f",
                        subtotalSnacks
                )
        );
        lblTotal.setText(
                String.format(
                        "Total: $%.2f",
                        total
                )
        );
    }
    
    //Métodos para obtener los snacks y sus cantidades
    public boolean tieneCanguilSeleccionado() {
        return chkCanguil.isSelected();
    }

    public boolean tieneGaseosaSeleccionada() {
        return chkGaseosa.isSelected();
    }

    public boolean tieneNachosSeleccionados() {
        return chkNachos.isSelected();
    }
    
    public int obtenerCantidadCanguil() {
        return (int) spnCanguil.getValue();
    }

    public int obtenerCantidadGaseosa() {
        return (int) spnGaseosa.getValue();
    }

    public int obtenerCantidadNachos() {
        return (int) spnNachos.getValue();
    }
    
    public void agregarEventoCalcular(java.awt.event.ActionListener listener) {
        btnCalcular.addActionListener(listener);
    }

    public void agregarEventoContinuar(java.awt.event.ActionListener listener) {
        btnContinuar.addActionListener(listener);
    }

    public void agregarEventoVolver(java.awt.event.ActionListener listener) {
        btnVolver.addActionListener(listener);
    }

    public void mostrarMensaje(String mensaje) {
        javax.swing.JOptionPane.showMessageDialog(this, mensaje);
    }
    
    private void configurarSpinnersSnacks() {
        spnCanguil.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
        spnGaseosa.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
        spnNachos.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
    }
    
    private void configurarEventosSnacks() {
        chkCanguil.addActionListener(e -> {
            if (chkCanguil.isSelected() && (int) spnCanguil.getValue() == 0) {
                spnCanguil.setValue(1);
            }

            if (!chkCanguil.isSelected()) {
                spnCanguil.setValue(0);
            }
        });

        chkGaseosa.addActionListener(e -> {
            if (chkGaseosa.isSelected() && (int) spnGaseosa.getValue() == 0) {
                spnGaseosa.setValue(1);
            }

            if (!chkGaseosa.isSelected()) {
                spnGaseosa.setValue(0);
            }
        });

        chkNachos.addActionListener(e -> {
            if (chkNachos.isSelected() && (int) spnNachos.getValue() == 0) {
                spnNachos.setValue(1);
            }

            if (!chkNachos.isSelected()) {
                spnNachos.setValue(0);
            }
        });
    }
    
}



