package fis.poo.cinefis.vista;

import fis.poo.cinefis.modelo.Funcion;
import java.util.ArrayList;
import javax.swing.JButton;

public class VistaSeleccionAsientos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = 
                java.util.logging.Logger.getLogger(VistaSeleccionAsientos.class.getName());
    
    private final java.util.ArrayList<String> asientosSeleccionados =
        new java.util.ArrayList<>();

    private final java.util.ArrayList<String> asientosOcupados =
        new java.util.ArrayList<>();

    private static final int LIMITE_ASIENTOS = 5;

    private static final java.awt.Color COLOR_DISPONIBLE =
        new java.awt.Color(30, 40, 52);

    private static final java.awt.Color COLOR_SELECCIONADO =
        new java.awt.Color(218, 165, 32);

    private static final java.awt.Color COLOR_OCUPADO =
        new java.awt.Color(120, 120, 120);
    
    
    /**
     * Creates new form VistaSeleccionAsientos
     */
    public VistaSeleccionAsientos() {
        initComponents();
        setTitle("CINEFIS - Selección de Asientos");
        setSize(900, 650);
        setLocationRelativeTo(null);
        setResizable(false);
        configurarEventosAsientos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblSubtitulo = new javax.swing.JLabel();
        panelDatosFuncion = new javax.swing.JPanel();
        lblPelicula = new javax.swing.JLabel();
        lblSala = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        panelAsientos = new javax.swing.JPanel();
        lblPantalla = new javax.swing.JLabel();
        lblLineaPantalla = new javax.swing.JLabel();
        btnA1 = new javax.swing.JButton();
        btnB1 = new javax.swing.JButton();
        btnC1 = new javax.swing.JButton();
        btnD1 = new javax.swing.JButton();
        btnA2 = new javax.swing.JButton();
        btnB2 = new javax.swing.JButton();
        btnC2 = new javax.swing.JButton();
        btnD2 = new javax.swing.JButton();
        btnB3 = new javax.swing.JButton();
        btnD3 = new javax.swing.JButton();
        btnA3 = new javax.swing.JButton();
        btnC3 = new javax.swing.JButton();
        btnB4 = new javax.swing.JButton();
        btnA4 = new javax.swing.JButton();
        btnC4 = new javax.swing.JButton();
        btnD4 = new javax.swing.JButton();
        btnA5 = new javax.swing.JButton();
        btnB5 = new javax.swing.JButton();
        btnD5 = new javax.swing.JButton();
        btnC5 = new javax.swing.JButton();
        lblAsientoSeleccionado = new javax.swing.JLabel();
        panelBotones = new javax.swing.JPanel();
        btnContinuar = new javax.swing.JButton();
        btnVolverCatalogo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CINEFIS - Selección de Asientos");
        setMaximumSize(new java.awt.Dimension(900, 650));
        setMinimumSize(new java.awt.Dimension(900, 650));
        setPreferredSize(new java.awt.Dimension(900, 650));
        setResizable(false);

        panelPrincipal.setBackground(new java.awt.Color(10, 14, 20));
        panelPrincipal.setMaximumSize(new java.awt.Dimension(900, 650));
        panelPrincipal.setMinimumSize(new java.awt.Dimension(900, 650));
        panelPrincipal.setPreferredSize(new java.awt.Dimension(900, 650));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 38)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(218, 165, 32));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("CINEFIS");

        lblSubtitulo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblSubtitulo.setForeground(new java.awt.Color(240, 240, 240));
        lblSubtitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSubtitulo.setText("Selección de asientos");

        panelDatosFuncion.setBackground(new java.awt.Color(18, 28, 38));
        panelDatosFuncion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(218, 165, 32)));
        panelDatosFuncion.setPreferredSize(new java.awt.Dimension(760, 100));

        lblPelicula.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPelicula.setForeground(new java.awt.Color(240, 240, 240));
        lblPelicula.setText("Película: ---");

        lblSala.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSala.setForeground(new java.awt.Color(240, 240, 240));
        lblSala.setText("Sala: ---");

        lblFecha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(240, 240, 240));
        lblFecha.setText("Fecha: ---");

        lblHora.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHora.setForeground(new java.awt.Color(240, 240, 240));
        lblHora.setText("Hora: ---");

        lblPrecio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPrecio.setForeground(new java.awt.Color(240, 240, 240));
        lblPrecio.setText("Precio base: ---");

        javax.swing.GroupLayout panelDatosFuncionLayout = new javax.swing.GroupLayout(panelDatosFuncion);
        panelDatosFuncion.setLayout(panelDatosFuncionLayout);
        panelDatosFuncionLayout.setHorizontalGroup(
            panelDatosFuncionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosFuncionLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelDatosFuncionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPelicula)
                    .addComponent(lblHora))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelDatosFuncionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelDatosFuncionLayout.createSequentialGroup()
                        .addComponent(lblPrecio)
                        .addGap(361, 361, 361))
                    .addGroup(panelDatosFuncionLayout.createSequentialGroup()
                        .addComponent(lblSala)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblFecha)
                        .addGap(152, 152, 152))))
        );
        panelDatosFuncionLayout.setVerticalGroup(
            panelDatosFuncionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosFuncionLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelDatosFuncionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPelicula)
                    .addComponent(lblSala)
                    .addComponent(lblFecha))
                .addGap(18, 18, 18)
                .addGroup(panelDatosFuncionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHora)
                    .addComponent(lblPrecio))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        panelAsientos.setBackground(new java.awt.Color(18, 28, 38));
        panelAsientos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(218, 165, 32)));
        panelAsientos.setPreferredSize(new java.awt.Dimension(760, 310));

        lblPantalla.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblPantalla.setForeground(new java.awt.Color(218, 165, 32));
        lblPantalla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPantalla.setText("PANTALLA");

        lblLineaPantalla.setBackground(new java.awt.Color(240, 240, 240));
        lblLineaPantalla.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblLineaPantalla.setForeground(new java.awt.Color(240, 240, 240));
        lblLineaPantalla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLineaPantalla.setText("________________________________________________________");

        btnA1.setBackground(new java.awt.Color(30, 40, 52));
        btnA1.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnA1.setForeground(new java.awt.Color(240, 240, 240));
        btnA1.setText("A1");
        btnA1.setFocusPainted(false);
        btnA1.setMaximumSize(new java.awt.Dimension(77, 24));
        btnA1.setMinimumSize(new java.awt.Dimension(74, 24));
        btnA1.setPreferredSize(new java.awt.Dimension(77, 24));
        btnA1.addActionListener(this::btnA1ActionPerformed);

        btnB1.setBackground(new java.awt.Color(30, 40, 52));
        btnB1.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnB1.setForeground(new java.awt.Color(240, 240, 240));
        btnB1.setText("B1");
        btnB1.setFocusPainted(false);
        btnB1.setMaximumSize(new java.awt.Dimension(77, 24));
        btnB1.setMinimumSize(new java.awt.Dimension(74, 24));
        btnB1.setPreferredSize(new java.awt.Dimension(77, 24));
        btnB1.addActionListener(this::btnB1ActionPerformed);

        btnC1.setBackground(new java.awt.Color(30, 40, 52));
        btnC1.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnC1.setForeground(new java.awt.Color(240, 240, 240));
        btnC1.setText("C1");
        btnC1.setFocusPainted(false);
        btnC1.setMaximumSize(new java.awt.Dimension(77, 24));
        btnC1.setMinimumSize(new java.awt.Dimension(74, 24));
        btnC1.setPreferredSize(new java.awt.Dimension(77, 24));
        btnC1.addActionListener(this::btnC1ActionPerformed);

        btnD1.setBackground(new java.awt.Color(30, 40, 52));
        btnD1.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnD1.setForeground(new java.awt.Color(240, 240, 240));
        btnD1.setText("D1");
        btnD1.setFocusPainted(false);
        btnD1.setMaximumSize(new java.awt.Dimension(77, 24));
        btnD1.setMinimumSize(new java.awt.Dimension(74, 24));
        btnD1.setPreferredSize(new java.awt.Dimension(77, 24));
        btnD1.addActionListener(this::btnD1ActionPerformed);

        btnA2.setBackground(new java.awt.Color(30, 40, 52));
        btnA2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnA2.setForeground(new java.awt.Color(240, 240, 240));
        btnA2.setText("A2");
        btnA2.setFocusPainted(false);
        btnA2.setMaximumSize(new java.awt.Dimension(77, 24));
        btnA2.setMinimumSize(new java.awt.Dimension(74, 24));
        btnA2.setPreferredSize(new java.awt.Dimension(77, 24));
        btnA2.addActionListener(this::btnA2ActionPerformed);

        btnB2.setBackground(new java.awt.Color(30, 40, 52));
        btnB2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnB2.setForeground(new java.awt.Color(240, 240, 240));
        btnB2.setText("B2");
        btnB2.setFocusPainted(false);
        btnB2.setMaximumSize(new java.awt.Dimension(77, 24));
        btnB2.setMinimumSize(new java.awt.Dimension(74, 24));
        btnB2.setPreferredSize(new java.awt.Dimension(77, 24));
        btnB2.addActionListener(this::btnB2ActionPerformed);

        btnC2.setBackground(new java.awt.Color(30, 40, 52));
        btnC2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnC2.setForeground(new java.awt.Color(240, 240, 240));
        btnC2.setText("C2");
        btnC2.setFocusPainted(false);
        btnC2.setMaximumSize(new java.awt.Dimension(77, 24));
        btnC2.setMinimumSize(new java.awt.Dimension(74, 24));
        btnC2.setPreferredSize(new java.awt.Dimension(77, 24));
        btnC2.addActionListener(this::btnC2ActionPerformed);

        btnD2.setBackground(new java.awt.Color(30, 40, 52));
        btnD2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnD2.setForeground(new java.awt.Color(240, 240, 240));
        btnD2.setText("D2");
        btnD2.setFocusPainted(false);
        btnD2.setMaximumSize(new java.awt.Dimension(77, 24));
        btnD2.setMinimumSize(new java.awt.Dimension(74, 24));
        btnD2.setPreferredSize(new java.awt.Dimension(77, 24));
        btnD2.addActionListener(this::btnD2ActionPerformed);

        btnB3.setBackground(new java.awt.Color(30, 40, 52));
        btnB3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnB3.setForeground(new java.awt.Color(240, 240, 240));
        btnB3.setText("B3");
        btnB3.setFocusPainted(false);
        btnB3.setMaximumSize(new java.awt.Dimension(77, 24));
        btnB3.setMinimumSize(new java.awt.Dimension(74, 24));
        btnB3.setPreferredSize(new java.awt.Dimension(77, 24));
        btnB3.addActionListener(this::btnB3ActionPerformed);

        btnD3.setBackground(new java.awt.Color(30, 40, 52));
        btnD3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnD3.setForeground(new java.awt.Color(240, 240, 240));
        btnD3.setText("D3");
        btnD3.setFocusPainted(false);
        btnD3.setMaximumSize(new java.awt.Dimension(77, 24));
        btnD3.setMinimumSize(new java.awt.Dimension(74, 24));
        btnD3.setPreferredSize(new java.awt.Dimension(77, 24));
        btnD3.addActionListener(this::btnD3ActionPerformed);

        btnA3.setBackground(new java.awt.Color(30, 40, 52));
        btnA3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnA3.setForeground(new java.awt.Color(240, 240, 240));
        btnA3.setText("A3");
        btnA3.setFocusPainted(false);
        btnA3.setMaximumSize(new java.awt.Dimension(77, 24));
        btnA3.setMinimumSize(new java.awt.Dimension(74, 24));
        btnA3.setPreferredSize(new java.awt.Dimension(77, 24));
        btnA3.addActionListener(this::btnA3ActionPerformed);

        btnC3.setBackground(new java.awt.Color(30, 40, 52));
        btnC3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnC3.setForeground(new java.awt.Color(240, 240, 240));
        btnC3.setText("C3");
        btnC3.setFocusPainted(false);
        btnC3.setMaximumSize(new java.awt.Dimension(77, 24));
        btnC3.setMinimumSize(new java.awt.Dimension(74, 24));
        btnC3.setPreferredSize(new java.awt.Dimension(77, 24));
        btnC3.addActionListener(this::btnC3ActionPerformed);

        btnB4.setBackground(new java.awt.Color(30, 40, 52));
        btnB4.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnB4.setForeground(new java.awt.Color(240, 240, 240));
        btnB4.setText("B4");
        btnB4.setFocusPainted(false);
        btnB4.setMaximumSize(new java.awt.Dimension(77, 24));
        btnB4.setMinimumSize(new java.awt.Dimension(74, 24));
        btnB4.setPreferredSize(new java.awt.Dimension(77, 24));
        btnB4.addActionListener(this::btnB4ActionPerformed);

        btnA4.setBackground(new java.awt.Color(30, 40, 52));
        btnA4.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnA4.setForeground(new java.awt.Color(240, 240, 240));
        btnA4.setText("A4");
        btnA4.setFocusPainted(false);
        btnA4.setMaximumSize(new java.awt.Dimension(77, 24));
        btnA4.setMinimumSize(new java.awt.Dimension(74, 24));
        btnA4.setPreferredSize(new java.awt.Dimension(77, 24));
        btnA4.addActionListener(this::btnA4ActionPerformed);

        btnC4.setBackground(new java.awt.Color(30, 40, 52));
        btnC4.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnC4.setForeground(new java.awt.Color(240, 240, 240));
        btnC4.setText("C4");
        btnC4.setFocusPainted(false);
        btnC4.setMaximumSize(new java.awt.Dimension(77, 24));
        btnC4.setMinimumSize(new java.awt.Dimension(74, 24));
        btnC4.setPreferredSize(new java.awt.Dimension(77, 24));
        btnC4.addActionListener(this::btnC4ActionPerformed);

        btnD4.setBackground(new java.awt.Color(30, 40, 52));
        btnD4.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnD4.setForeground(new java.awt.Color(240, 240, 240));
        btnD4.setText("D4");
        btnD4.setFocusPainted(false);
        btnD4.setMaximumSize(new java.awt.Dimension(77, 24));
        btnD4.setMinimumSize(new java.awt.Dimension(74, 24));
        btnD4.setPreferredSize(new java.awt.Dimension(77, 24));
        btnD4.addActionListener(this::btnD4ActionPerformed);

        btnA5.setBackground(new java.awt.Color(30, 40, 52));
        btnA5.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnA5.setForeground(new java.awt.Color(240, 240, 240));
        btnA5.setText("A5");
        btnA5.setFocusPainted(false);
        btnA5.setMaximumSize(new java.awt.Dimension(77, 24));
        btnA5.setMinimumSize(new java.awt.Dimension(74, 24));
        btnA5.setPreferredSize(new java.awt.Dimension(77, 24));
        btnA5.addActionListener(this::btnA5ActionPerformed);

        btnB5.setBackground(new java.awt.Color(30, 40, 52));
        btnB5.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnB5.setForeground(new java.awt.Color(240, 240, 240));
        btnB5.setText("B5");
        btnB5.setFocusPainted(false);
        btnB5.setMaximumSize(new java.awt.Dimension(77, 24));
        btnB5.setMinimumSize(new java.awt.Dimension(74, 24));
        btnB5.setPreferredSize(new java.awt.Dimension(77, 24));
        btnB5.addActionListener(this::btnB5ActionPerformed);

        btnD5.setBackground(new java.awt.Color(30, 40, 52));
        btnD5.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnD5.setForeground(new java.awt.Color(240, 240, 240));
        btnD5.setText("D5");
        btnD5.setFocusPainted(false);
        btnD5.setMaximumSize(new java.awt.Dimension(77, 24));
        btnD5.setMinimumSize(new java.awt.Dimension(74, 24));
        btnD5.setPreferredSize(new java.awt.Dimension(77, 24));
        btnD5.addActionListener(this::btnD5ActionPerformed);

        btnC5.setBackground(new java.awt.Color(30, 40, 52));
        btnC5.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnC5.setForeground(new java.awt.Color(240, 240, 240));
        btnC5.setText("C5");
        btnC5.setFocusPainted(false);
        btnC5.setMaximumSize(new java.awt.Dimension(77, 24));
        btnC5.setMinimumSize(new java.awt.Dimension(74, 24));
        btnC5.setPreferredSize(new java.awt.Dimension(77, 24));
        btnC5.addActionListener(this::btnC5ActionPerformed);

        lblAsientoSeleccionado.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblAsientoSeleccionado.setForeground(new java.awt.Color(218, 165, 32));
        lblAsientoSeleccionado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAsientoSeleccionado.setText("Asientos seleccionados: Ninguno");

        javax.swing.GroupLayout panelAsientosLayout = new javax.swing.GroupLayout(panelAsientos);
        panelAsientos.setLayout(panelAsientosLayout);
        panelAsientosLayout.setHorizontalGroup(
            panelAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAsientosLayout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addGroup(panelAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnA1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnB1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnC1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnD1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnA2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnB2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnC2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnD2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnA3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnB3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnC3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnD3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnA4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnB4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnC4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnD4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnB5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnA5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnD5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnC5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(152, 152, 152))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAsientosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblPantalla)
                .addGap(325, 325, 325))
            .addGroup(panelAsientosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAsientoSeleccionado)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAsientosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLineaPantalla)
                .addGap(176, 176, 176))
        );
        panelAsientosLayout.setVerticalGroup(
            panelAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAsientosLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblPantalla)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLineaPantalla)
                .addGap(28, 28, 28)
                .addGroup(panelAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAsientosLayout.createSequentialGroup()
                        .addComponent(btnA5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btnB5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btnC5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnD5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAsientosLayout.createSequentialGroup()
                            .addComponent(btnA1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnB1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(btnC1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnD1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAsientosLayout.createSequentialGroup()
                            .addComponent(btnA2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnB2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(btnC2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnD2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAsientosLayout.createSequentialGroup()
                            .addComponent(btnA3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnB3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(btnC3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnD3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelAsientosLayout.createSequentialGroup()
                            .addComponent(btnA4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnB4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(btnC4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnD4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblAsientoSeleccionado)
                .addContainerGap())
        );

        panelBotones.setBackground(new java.awt.Color(10, 14, 20));

        btnContinuar.setBackground(new java.awt.Color(218, 165, 32));
        btnContinuar.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnContinuar.setText("CONTINUAR");
        btnContinuar.setFocusPainted(false);

        btnVolverCatalogo.setBackground(new java.awt.Color(30, 40, 52));
        btnVolverCatalogo.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnVolverCatalogo.setForeground(new java.awt.Color(240, 240, 240));
        btnVolverCatalogo.setText("VOLVER AL CATÁLOGO");
        btnVolverCatalogo.setFocusPainted(false);

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addComponent(btnContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVolverCatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVolverCatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelAsientos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelDatosFuncion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(63, 63, 63))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSubtitulo)
                            .addComponent(lblTitulo))
                        .addGap(367, 367, 367))))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSubtitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelDatosFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelAsientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 914, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnA1ActionPerformed

    private void btnB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnB1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnB1ActionPerformed

    private void btnC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnC1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnC1ActionPerformed

    private void btnD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnD1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnD1ActionPerformed

    private void btnA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnA2ActionPerformed

    private void btnB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnB2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnB2ActionPerformed

    private void btnC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnC2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnC2ActionPerformed

    private void btnD2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnD2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnD2ActionPerformed

    private void btnB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnB3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnB3ActionPerformed

    private void btnD3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnD3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnD3ActionPerformed

    private void btnA3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnA3ActionPerformed

    private void btnC3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnC3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnC3ActionPerformed

    private void btnB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnB4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnB4ActionPerformed

    private void btnA4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnA4ActionPerformed

    private void btnC4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnC4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnC4ActionPerformed

    private void btnD4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnD4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnD4ActionPerformed

    private void btnA5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnA5ActionPerformed

    private void btnB5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnB5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnB5ActionPerformed

    private void btnD5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnD5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnD5ActionPerformed

    private void btnC5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnC5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnC5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaSeleccionAsientos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnA1;
    private javax.swing.JButton btnA2;
    private javax.swing.JButton btnA3;
    private javax.swing.JButton btnA4;
    private javax.swing.JButton btnA5;
    private javax.swing.JButton btnB1;
    private javax.swing.JButton btnB2;
    private javax.swing.JButton btnB3;
    private javax.swing.JButton btnB4;
    private javax.swing.JButton btnB5;
    private javax.swing.JButton btnC1;
    private javax.swing.JButton btnC2;
    private javax.swing.JButton btnC3;
    private javax.swing.JButton btnC4;
    private javax.swing.JButton btnC5;
    private javax.swing.JButton btnContinuar;
    private javax.swing.JButton btnD1;
    private javax.swing.JButton btnD2;
    private javax.swing.JButton btnD3;
    private javax.swing.JButton btnD4;
    private javax.swing.JButton btnD5;
    private javax.swing.JButton btnVolverCatalogo;
    private javax.swing.JLabel lblAsientoSeleccionado;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblLineaPantalla;
    private javax.swing.JLabel lblPantalla;
    private javax.swing.JLabel lblPelicula;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblSala;
    private javax.swing.JLabel lblSubtitulo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelAsientos;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelDatosFuncion;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables
    

    private void seleccionarAsiento(String asiento, JButton boton) {
        if (asientosOcupados.contains(asiento)) {
            mostrarMensaje(
                    "El asiento " + asiento + " ya está ocupado."
            );
            return;
        }

        if (asientosSeleccionados.contains(asiento)) {
            asientosSeleccionados.remove(asiento);
            boton.setBackground(COLOR_DISPONIBLE);

        } else {
            if (asientosSeleccionados.size() >= LIMITE_ASIENTOS) {
                mostrarMensaje(
                        "Solo puede seleccionar máximo "
                        + LIMITE_ASIENTOS
                        + " asientos."
                );
                return;
            }
            asientosSeleccionados.add(asiento);
            boton.setBackground(COLOR_SELECCIONADO);
        }
        actualizarTextoAsientos();
    }

    private void actualizarTextoAsientos() {
        if (asientosSeleccionados.isEmpty()) {
            lblAsientoSeleccionado.setText("Asientos seleccionados: Ninguno");
        } else {
            lblAsientoSeleccionado.setText("Asientos seleccionados: " + String.join(", ", asientosSeleccionados));
        }
    }
    
    public void configurarEventosAsientos() {
        btnA1.addActionListener(e -> seleccionarAsiento("A1", btnA1));
        btnA2.addActionListener(e -> seleccionarAsiento("A2", btnA2));
        btnA3.addActionListener(e -> seleccionarAsiento("A3", btnA3));
        btnA4.addActionListener(e -> seleccionarAsiento("A4", btnA4));
        btnA5.addActionListener(e -> seleccionarAsiento("A5", btnA5));

        btnB1.addActionListener(e -> seleccionarAsiento("B1", btnB1));
        btnB2.addActionListener(e -> seleccionarAsiento("B2", btnB2));
        btnB3.addActionListener(e -> seleccionarAsiento("B3", btnB3));
        btnB4.addActionListener(e -> seleccionarAsiento("B4", btnB4));
        btnB5.addActionListener(e -> seleccionarAsiento("B5", btnB5));

        btnC1.addActionListener(e -> seleccionarAsiento("C1", btnC1));
        btnC2.addActionListener(e -> seleccionarAsiento("C2", btnC2));
        btnC3.addActionListener(e -> seleccionarAsiento("C3", btnC3));
        btnC4.addActionListener(e -> seleccionarAsiento("C4", btnC4));
        btnC5.addActionListener(e -> seleccionarAsiento("C5", btnC5));

        btnD1.addActionListener(e -> seleccionarAsiento("D1", btnD1));
        btnD2.addActionListener(e -> seleccionarAsiento("D2", btnD2));
        btnD3.addActionListener(e -> seleccionarAsiento("D3", btnD3));
        btnD4.addActionListener(e -> seleccionarAsiento("D4", btnD4));
        btnD5.addActionListener(e -> seleccionarAsiento("D5", btnD5));
    }

    public void mostrarFuncion(Funcion funcion) {
        if (funcion == null) {
            lblPelicula.setText("Película: No seleccionada");
            lblSala.setText("Sala: No seleccionada");
            lblFecha.setText("Fecha: No disponible");
            lblHora.setText("Hora: No disponible");
            lblPrecio.setText("Precio base: $0.00");
            return;
        }

        lblPelicula.setText(
                "Película: " + funcion.getPelicula().getTitulo()
        );

        lblSala.setText(
                "Sala: " + funcion.getSala().getNombre()
        );

        lblFecha.setText(
                "Fecha: " + funcion.getFecha()
        );

        lblHora.setText(
                "Hora: " + funcion.getHora()
        );

        lblPrecio.setText(
                String.format(
                        "Precio base: $%.2f",
                        funcion.getPrecioBase()
                )
        );
    }
    
    public ArrayList<String> obtenerAsientosSeleccionados() {
        //devuelve una copia para que otra clse no modifique directamente la lista
        //interna de la vista
        return new ArrayList<>(asientosSeleccionados);
    }
    
    public void establecerAsientosSeleccionados(ArrayList<String> asientos) {
        asientosSeleccionados.clear();
        if (asientos != null) {
            for (String asiento : asientos) {
                if (!asientosOcupados.contains(asiento)) {
                    asientosSeleccionados.add(asiento);
                }
            }
        }
        actualizarEstadoBotones();
    }
    
    //Cuando el trabajador vuelva desde VistaCompra, los asientos
    //que seleccionó estarán dorados
    public void establecerAsientosOcupados(ArrayList<String> ocupados) {
        asientosOcupados.clear();

        if (ocupados != null) {
            asientosOcupados.addAll(ocupados);
        }

        actualizarEstadoBotones();
    }
    
    private void actualizarEstadoBotones() {
        for (JButton boton : obtenerBotonesAsientos()) {
            String asiento = boton.getText().trim();
            if (asientosOcupados.contains(asiento)) {
                boton.setBackground(COLOR_OCUPADO);
                boton.setEnabled(false);
                boton.setToolTipText("Asiento ocupado");
            } else if (asientosSeleccionados.contains(asiento)) {
                boton.setBackground(COLOR_SELECCIONADO);
                boton.setEnabled(true);
                boton.setToolTipText("Asiento seleccionado");
            } else {
                boton.setBackground(COLOR_DISPONIBLE);
                boton.setEnabled(true);
                boton.setToolTipText("Asiento disponible");
            }
        }
        actualizarTextoAsientos();
    }
    
    private void limpiarSeleccionVisual() {
        asientosSeleccionados.clear();

        java.awt.Color colorNormal =
                new java.awt.Color(30, 40, 52);

        javax.swing.JButton[] botones = {
            btnA1, btnA2, btnA3, btnA4, btnA5,
            btnB1, btnB2, btnB3, btnB4, btnB5,
            btnC1, btnC2, btnC3, btnC4, btnC5,
            btnD1, btnD2, btnD3, btnD4, btnD5
        };

        for (javax.swing.JButton boton : botones) {
            boton.setBackground(colorNormal);
        }
    }
    
    private void seleccionarAsientoPorCodigo(String asiento) {
        javax.swing.JButton boton = obtenerBotonAsiento(asiento);

        if (boton == null) {
            return;
        }

        if (!asientosSeleccionados.contains(asiento)) {
            asientosSeleccionados.add(asiento);
            boton.setBackground(new java.awt.Color(218, 165, 32));
        }
    }
    
    private JButton obtenerBotonAsiento(String asiento) {
        return switch (asiento) {
            case "A1" -> btnA1;
            case "A2" -> btnA2;
            case "A3" -> btnA3;
            case "A4" -> btnA4;
            case "A5" -> btnA5;
            case "B1" -> btnB1;
            case "B2" -> btnB2;
            case "B3" -> btnB3;
            case "B4" -> btnB4;
            case "B5" -> btnB5;
            case "C1" -> btnC1;
            case "C2" -> btnC2;
            case "C3" -> btnC3;
            case "C4" -> btnC4;
            case "C5" -> btnC5;
            case "D1" -> btnD1;
            case "D2" -> btnD2;
            case "D3" -> btnD3;
            case "D4" -> btnD4;
            case "D5" -> btnD5;
            default -> null;
        };
    }
    
    private JButton[] obtenerBotonesAsientos() {
        return new JButton[]{
            btnA1, btnA2, btnA3, btnA4, btnA5,
            btnB1, btnB2, btnB3, btnB4, btnB5,
            btnC1, btnC2, btnC3, btnC4, btnC5,
            btnD1, btnD2, btnD3, btnD4, btnD5
        };
    }

    public void agregarEventoContinuar(java.awt.event.ActionListener listener) {
        btnContinuar.addActionListener(listener);
    }

    public void agregarEventoVolverCatalogo(java.awt.event.ActionListener listener) {
        btnVolverCatalogo.addActionListener(listener);
    }

    public void mostrarMensaje(String mensaje) {
        javax.swing.JOptionPane.showMessageDialog(this, mensaje);
    }
}
