package fis.poo.cinefis.vista;

import fis.poo.cinefis.modelo.Funcion;
import fis.poo.cinefis.modelo.Pelicula;
import fis.poo.cinefis.repositorio.RepositorioFunciones;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;


public class VistaCatalogo extends javax.swing.JFrame {
    
    private ArrayList<Funcion> listaFunciones = new ArrayList<>();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaCatalogo.class.getName());

    /**
     * Creates new form VistaMenuPrincipal
     */
    public VistaCatalogo() {
        initComponents();
        
        setTitle("CINEFIS - Catálogo de Películas");
        setSize(1200, 700);
        setLocationRelativeTo(null);
        setResizable(false);
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        configurarTabla();
        configurarTextoSinopsis();
        configurarEventoSeleccionTabla(); 
        RepositorioFunciones repo = new RepositorioFunciones();
        mostrarFunciones(repo.obtenerFunciones());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblSubtitulo = new javax.swing.JLabel();
        panelTabla = new javax.swing.JPanel();
        lblFunciones = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaFunciones = new javax.swing.JTable();
        lblSubtitulo1 = new javax.swing.JLabel();
        panelPoster = new javax.swing.JPanel();
        lblTituloPoster = new javax.swing.JLabel();
        lblPoster = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaSinopsis = new javax.swing.JTextArea();
        lblTituloPoster1 = new javax.swing.JLabel();
        panelBotones = new javax.swing.JPanel();
        btnSeleccionarFuncion = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CINEFIS - Catálogo de Películas");
        setMinimumSize(new java.awt.Dimension(1050, 650));
        setResizable(false);

        panelPrincipal.setBackground(new java.awt.Color(10, 14, 20));
        panelPrincipal.setPreferredSize(new java.awt.Dimension(1050, 650));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 38)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(218, 165, 32));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("CINEFIS");

        lblSubtitulo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblSubtitulo.setForeground(new java.awt.Color(240, 240, 240));
        lblSubtitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSubtitulo.setText("Catálogo de películas y funciones disponibles");

        panelTabla.setBackground(new java.awt.Color(18, 28, 38));
        panelTabla.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(218, 165, 32), 1, true));
        panelTabla.setPreferredSize(new java.awt.Dimension(680, 430));

        lblFunciones.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblFunciones.setForeground(new java.awt.Color(240, 240, 240));
        lblFunciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFunciones.setText("Funciones disponibles");

        tablaFunciones.setBackground(new java.awt.Color(245, 245, 245));
        tablaFunciones.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tablaFunciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaFunciones.setGridColor(new java.awt.Color(180, 180, 180));
        tablaFunciones.setMinimumSize(new java.awt.Dimension(630, 330));
        tablaFunciones.setPreferredSize(new java.awt.Dimension(630, 330));
        tablaFunciones.setRowHeight(28);
        tablaFunciones.setSelectionBackground(new java.awt.Color(218, 165, 32));
        jScrollPane1.setViewportView(tablaFunciones);

        lblSubtitulo1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblSubtitulo1.setForeground(new java.awt.Color(240, 240, 240));
        lblSubtitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSubtitulo1.setText("Seleccione una función:");

        javax.swing.GroupLayout panelTablaLayout = new javax.swing.GroupLayout(panelTabla);
        panelTabla.setLayout(panelTablaLayout);
        panelTablaLayout.setHorizontalGroup(
            panelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTablaLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 782, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTablaLayout.createSequentialGroup()
                        .addComponent(lblSubtitulo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblFunciones)
                        .addGap(206, 206, 206))))
        );
        panelTablaLayout.setVerticalGroup(
            panelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTablaLayout.createSequentialGroup()
                        .addComponent(lblFunciones)
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTablaLayout.createSequentialGroup()
                        .addComponent(lblSubtitulo1)
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelPoster.setBackground(new java.awt.Color(18, 28, 38));
        panelPoster.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(218, 165, 32)));
        panelPoster.setPreferredSize(new java.awt.Dimension(280, 430));

        lblTituloPoster.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblTituloPoster.setForeground(new java.awt.Color(240, 240, 240));
        lblTituloPoster.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloPoster.setText("Póster");

        lblPoster.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPoster.setForeground(new java.awt.Color(200, 200, 200));
        lblPoster.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txaSinopsis.setBackground(new java.awt.Color(18, 28, 38));
        txaSinopsis.setColumns(20);
        txaSinopsis.setForeground(new java.awt.Color(255, 255, 255));
        txaSinopsis.setRows(5);
        txaSinopsis.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(218, 165, 32)));
        jScrollPane2.setViewportView(txaSinopsis);

        lblTituloPoster1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblTituloPoster1.setForeground(new java.awt.Color(240, 240, 240));
        lblTituloPoster1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloPoster1.setText("Sinopsis");

        javax.swing.GroupLayout panelPosterLayout = new javax.swing.GroupLayout(panelPoster);
        panelPoster.setLayout(panelPosterLayout);
        panelPosterLayout.setHorizontalGroup(
            panelPosterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPosterLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelPosterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTituloPoster1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTituloPoster)
                    .addGroup(panelPosterLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(lblPoster, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        panelPosterLayout.setVerticalGroup(
            panelPosterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPosterLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblTituloPoster)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPoster, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTituloPoster1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        panelBotones.setBackground(new java.awt.Color(10, 14, 20));

        btnSeleccionarFuncion.setBackground(new java.awt.Color(218, 165, 32));
        btnSeleccionarFuncion.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnSeleccionarFuncion.setText("CONTINUAR");
        btnSeleccionarFuncion.setFocusPainted(false);
        btnSeleccionarFuncion.setMaximumSize(new java.awt.Dimension(201, 88));
        btnSeleccionarFuncion.setMinimumSize(new java.awt.Dimension(201, 88));
        btnSeleccionarFuncion.setPreferredSize(new java.awt.Dimension(201, 88));
        btnSeleccionarFuncion.addActionListener(this::btnSeleccionarFuncionActionPerformed);

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotonesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSeleccionarFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addComponent(btnSeleccionarFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        btnSalir.setBackground(new java.awt.Color(218, 165, 32));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnSalir.setText("SALIR");
        btnSalir.setFocusPainted(false);
        btnSalir.setMaximumSize(new java.awt.Dimension(111, 228));
        btnSalir.setMinimumSize(new java.awt.Dimension(172, 228));
        btnSalir.setPreferredSize(new java.awt.Dimension(172, 228));
        btnSalir.addActionListener(this::btnSalirActionPerformed);

        btnCerrarSesion.setBackground(new java.awt.Color(218, 165, 32));
        btnCerrarSesion.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnCerrarSesion.setText("CERRAR SESIÓN");
        btnCerrarSesion.setFocusPainted(false);
        btnCerrarSesion.setMaximumSize(new java.awt.Dimension(144, 228));
        btnCerrarSesion.setMinimumSize(new java.awt.Dimension(144, 222));
        btnCerrarSesion.setPreferredSize(new java.awt.Dimension(144, 228));
        btnCerrarSesion.addActionListener(this::btnCerrarSesionActionPerformed);

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(349, 349, 349)
                        .addComponent(lblSubtitulo))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(432, 432, 432)
                        .addComponent(lblTitulo)))
                .addContainerGap(464, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(panelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(panelTabla, javax.swing.GroupLayout.DEFAULT_SIZE, 796, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelPoster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSubtitulo)
                .addGap(18, 18, 18)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelPoster, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                    .addComponent(panelTabla, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 1126, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnSeleccionarFuncionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarFuncionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSeleccionarFuncionActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaCatalogo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSeleccionarFuncion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblFunciones;
    private javax.swing.JLabel lblPoster;
    private javax.swing.JLabel lblSubtitulo;
    private javax.swing.JLabel lblSubtitulo1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloPoster;
    private javax.swing.JLabel lblTituloPoster1;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelPoster;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelTabla;
    private javax.swing.JTable tablaFunciones;
    private javax.swing.JTextArea txaSinopsis;
    // End of variables declaration//GEN-END:variables
    public void agregarEventoSeleccionarFuncion(java.awt.event.ActionListener listener) {
        btnSeleccionarFuncion.addActionListener(listener);
    }

    public void agregarEventoCerrarSesion(java.awt.event.ActionListener listener) {
        btnCerrarSesion.addActionListener(listener);
    }

    public void agregarEventoSalir(java.awt.event.ActionListener listener) {
        btnSalir.addActionListener(listener);
    }

    public int obtenerFilaSeleccionada() {
        return tablaFunciones.getSelectedRow();
    }

    public void mostrarMensaje(String mensaje) {
        javax.swing.JOptionPane.showMessageDialog(this, mensaje);
    }
    
    private void configurarTabla() {
        DefaultTableModel modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                // La tabla del catálogo solo muestra datos
                return false;
            }
        };

        modelo.addColumn("Código");
        modelo.addColumn("Película");
        modelo.addColumn("Género");
        modelo.addColumn("Clasificación");
        modelo.addColumn("Sala");
        modelo.addColumn("Fecha");
        modelo.addColumn("Hora");
        modelo.addColumn("Precio");

        tablaFunciones.setModel(modelo);
        tablaFunciones.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        // Estilo general de la tabla
        tablaFunciones.setRowHeight(28);
        tablaFunciones.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));
        tablaFunciones.setBackground(new java.awt.Color(245, 245, 245));
        tablaFunciones.setForeground(new java.awt.Color(0, 0, 0));
        tablaFunciones.setGridColor(new java.awt.Color(220, 220, 220));

        // Color cuando se selecciona una fila
        tablaFunciones.setSelectionBackground(new java.awt.Color(218, 165, 32));
        tablaFunciones.setSelectionForeground(new java.awt.Color(0, 0, 0));

        // Encabezado de la tabla
        tablaFunciones.getTableHeader().setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13));
        tablaFunciones.getTableHeader().setBackground(new java.awt.Color(218, 165, 32));
        tablaFunciones.getTableHeader().setForeground(new java.awt.Color(0, 0, 0));

        // Evita que el usuario mueva o agrande columnas
        tablaFunciones.getTableHeader().setReorderingAllowed(false);
        tablaFunciones.getTableHeader().setResizingAllowed(false);

        // La tabla se adapta al ancho disponible
        tablaFunciones.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);

        // Anchos recomendados
        tablaFunciones.getColumnModel().getColumn(0).setPreferredWidth(60);   // Código
        tablaFunciones.getColumnModel().getColumn(1).setPreferredWidth(210);  // Película
        tablaFunciones.getColumnModel().getColumn(2).setPreferredWidth(120);  // Género
        tablaFunciones.getColumnModel().getColumn(3).setPreferredWidth(120);  // Clasificación
        tablaFunciones.getColumnModel().getColumn(4).setPreferredWidth(80);   // Sala
        tablaFunciones.getColumnModel().getColumn(5).setPreferredWidth(100);  // Fecha
        tablaFunciones.getColumnModel().getColumn(6).setPreferredWidth(70);   // Hora
        tablaFunciones.getColumnModel().getColumn(7).setPreferredWidth(70);   // Precio
    }
    
    
    public void mostrarFunciones(ArrayList<Funcion> funciones) {
        DefaultTableModel modelo = (DefaultTableModel) tablaFunciones.getModel();

        modelo.setRowCount(0);

        listaFunciones = new ArrayList<>(funciones);

        for (Funcion funcion : listaFunciones) {
            modelo.addRow(new Object[]{
                funcion.getCodigo(),
                funcion.getPelicula().getTitulo(),
                funcion.getPelicula().getGenero(),
                funcion.getPelicula().getClasificacion(),
                funcion.getSala().getNombre(),
                funcion.getFecha(),
                funcion.getHora(),
                String.format("$%.2f", funcion.getPrecioBase())
            });
        }

        lblPoster.setIcon(null);
        lblPoster.setText("Seleccione una función");
    }
    
    
    public Funcion obtenerFuncionSeleccionada() {
        int fila = tablaFunciones.getSelectedRow();

        if (fila == -1) {
            return null;
        }

        String codigoFuncion = tablaFunciones.getValueAt(fila, 0).toString();

        for (Funcion funcion : listaFunciones) {
            if (funcion.getCodigo().equals(codigoFuncion)) {
                return funcion;
            }
        }

        return null;
    }
    
    private void configurarTextoSinopsis(){
        txaSinopsis.setEditable(false);
        txaSinopsis.setLineWrap(true);
        txaSinopsis.setWrapStyleWord(true);
        txaSinopsis.setFocusable(false);
        txaSinopsis.setText("Seleccione una función para ver la sinopsis.");
    }
    
    private void mostrarInformacionPelicula(Funcion funcion) {
        if (funcion == null || funcion.getPelicula() == null) {

            lblPoster.setIcon(null);
            mostrarSinopsis("Seleccione una función para ver la sinopsis.");
            return;
        }

        mostrarPoster(funcion);
        mostrarSinopsis(funcion.getPelicula().getSinopsis());
    }
    
    public void mostrarSinopsis(String sinopsis) {
        if (sinopsis == null || sinopsis.isBlank()) {
            txaSinopsis.setText("Sinopsis no disponible.");
        } else {
            txaSinopsis.setText(sinopsis);
        }

        txaSinopsis.setCaretPosition(0);
    }
    
    private void mostrarPoster(Funcion funcion) {
        String nombreImagen = funcion.getPelicula().getImagen();

        lblPoster.setIcon(new ImageIcon(
            getClass().getResource("/imagenes/peliculas/" + nombreImagen)
        ));

        lblPoster.setText("");
    }
    
    private void configurarEventoSeleccionTabla() {
        tablaFunciones.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                Funcion funcion = obtenerFuncionSeleccionada();

                if (funcion != null) {
                    mostrarInformacionPelicula(funcion);
                }
            }
        });
    }
}
