package fis.poo.cinefis.vista;

import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

public class VistaResumenCompra extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaResumenCompra.class.getName());

    /**
     * Creates new form VistaResumenCompra
     */
    public VistaResumenCompra() {
        initComponents();
        setTitle("CINEFIS - Resumen de Compra");
        setSize(850, 650);
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblSubtitulo = new javax.swing.JLabel();
        panelResumen = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaResumen = new javax.swing.JTextArea();
        panelTotales = new javax.swing.JPanel();
        lblSubtotalEntradas = new javax.swing.JLabel();
        lblSubtotalSnacks = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        panelBotones = new javax.swing.JPanel();
        btnRegresar = new javax.swing.JButton();
        btnFinalizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CINEFIS - Resumen de Compra ");
        setMinimumSize(new java.awt.Dimension(850, 650));
        setResizable(false);

        panelPrincipal.setBackground(new java.awt.Color(10, 14, 20));
        panelPrincipal.setPreferredSize(new java.awt.Dimension(850, 650));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 38)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(218, 165, 32));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("CINEFIS");

        lblSubtitulo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblSubtitulo.setForeground(new java.awt.Color(240, 240, 240));
        lblSubtitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSubtitulo.setText("Resumen de compra");

        panelResumen.setBackground(new java.awt.Color(18, 28, 38));
        panelResumen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(218, 165, 32)));
        panelResumen.setPreferredSize(new java.awt.Dimension(730, 390));

        areaResumen.setEditable(false);
        areaResumen.setBackground(new java.awt.Color(18, 28, 38));
        areaResumen.setColumns(20);
        areaResumen.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        areaResumen.setForeground(new java.awt.Color(240, 240, 240));
        areaResumen.setLineWrap(true);
        areaResumen.setRows(5);
        areaResumen.setWrapStyleWord(true);
        jScrollPane1.setViewportView(areaResumen);

        javax.swing.GroupLayout panelResumenLayout = new javax.swing.GroupLayout(panelResumen);
        panelResumen.setLayout(panelResumenLayout);
        panelResumenLayout.setHorizontalGroup(
            panelResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResumenLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        panelResumenLayout.setVerticalGroup(
            panelResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResumenLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        panelTotales.setBackground(new java.awt.Color(18, 28, 38));
        panelTotales.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(218, 165, 32)));
        panelTotales.setPreferredSize(new java.awt.Dimension(730, 80));

        lblSubtotalEntradas.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblSubtotalEntradas.setForeground(new java.awt.Color(218, 165, 32));
        lblSubtotalEntradas.setText("Subtotal entradas: $0.00");

        lblSubtotalSnacks.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblSubtotalSnacks.setForeground(new java.awt.Color(218, 165, 32));
        lblSubtotalSnacks.setText("Subtotal snacks: $0.00");

        lblTotal.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(218, 165, 32));
        lblTotal.setText("Total a pagar: $0.00");

        javax.swing.GroupLayout panelTotalesLayout = new javax.swing.GroupLayout(panelTotales);
        panelTotales.setLayout(panelTotalesLayout);
        panelTotalesLayout.setHorizontalGroup(
            panelTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTotalesLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTotalesLayout.createSequentialGroup()
                        .addComponent(lblSubtotalEntradas)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelTotalesLayout.createSequentialGroup()
                        .addComponent(lblSubtotalSnacks)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 341, Short.MAX_VALUE)
                        .addComponent(lblTotal)
                        .addGap(28, 28, 28))))
        );
        panelTotalesLayout.setVerticalGroup(
            panelTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTotalesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSubtotalEntradas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSubtotalSnacks)
                    .addComponent(lblTotal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelBotones.setBackground(new java.awt.Color(10, 14, 20));

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        btnRegresar.setBackground(new java.awt.Color(30, 40, 52));
        btnRegresar.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(240, 240, 240));
        btnRegresar.setText("REGRESAR");
        btnRegresar.setFocusPainted(false);

        btnFinalizar.setBackground(new java.awt.Color(218, 165, 32));
        btnFinalizar.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnFinalizar.setText("FINALIZAR COMPRA");
        btnFinalizar.setFocusPainted(false);

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                        .addComponent(btnFinalizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRegresar)
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSubtitulo)
                            .addComponent(lblTitulo))
                        .addGap(345, 345, 345))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelTotales, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelResumen, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSubtitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelResumen, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelTotales, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFinalizar)
                    .addComponent(btnRegresar))
                .addGap(54, 54, 54)
                .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 862, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 662, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaResumenCompra().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaResumen;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSubtitulo;
    private javax.swing.JLabel lblSubtotalEntradas;
    private javax.swing.JLabel lblSubtotalSnacks;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelResumen;
    private javax.swing.JPanel panelTotales;
    // End of variables declaration//GEN-END:variables
    public void mostrarResumen(String resumen) {
        areaResumen.setText(resumen);
    }

    public void mostrarTotales(double subtotalEntradas, double subtotalSnacks, double total) {
        lblSubtotalEntradas.setText(String.format("Subtotal entradas: $%.2f", subtotalEntradas));
        lblSubtotalSnacks.setText(String.format("Subtotal snacks: $%.2f", subtotalSnacks));
        lblTotal.setText(String.format("Total a pagar: $%.2f", total));
    }
    
    public boolean confirmarVenta() {
        int respuesta =
                JOptionPane.showConfirmDialog(
                        this,
                        "¿Desea confirmar y registrar esta venta?",
                        "Confirmar venta",
                        javax.swing.JOptionPane.YES_NO_OPTION,
                        javax.swing.JOptionPane.QUESTION_MESSAGE
                );

        return respuesta == javax.swing.JOptionPane.YES_OPTION;
    }

    public void agregarEventoFinalizar(ActionListener listener) {
        btnFinalizar.addActionListener(listener);
    }

    public void agregarEventoRegresar(ActionListener listener) {
        btnRegresar.addActionListener(listener);
    }

    public void mostrarMensaje(String mensaje) {
        javax.swing.JOptionPane.showMessageDialog(this, mensaje);
    }
    
}
